name: Build Desktop App

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: sisky-desktop-linux
          path: dist/*.AppImage

  build-mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: sisky-desktop-mac
          path: dist/*.dmg

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        shell: powershell
        run: |
          $env:CI = "true"
          npm install --prefer-offline
      - name: Build
        shell: powershell
        run: |
          $env:GH_TOKEN = "${{ secrets.GITHUB_TOKEN }}"
          $env:CI = "true"
          npm run build
      - uses: actions/upload-artifact@v4
        with:
          name: sisky-desktop-windows
          path: dist/*.exe